## Housing Prices in the 50 US States
The goal of this project is to clean data, find median costs of houses sold in the US via brokerages, plot the results in graphs to show the difference in states, and to save the new dataset as a CSV to use it in other programs.

In [1]:
#import the tools we need.
import pandas as pd
import matplotlib as mlt
import numpy as np

In [2]:
import os
os.getcwd()

'C:\\Users\\shell'

In [3]:
realtor_data = pd.read_csv("realtor_data.csv") #import the dataset

In [4]:
realtor_data.head() #check the dataset

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
0,103378.0,for_sale,105000.0,3.0,2.0,0.12,1962661.0,Adjuntas,Puerto Rico,601.0,920.0,NaN
1,52707.0,for_sale,80000.0,4.0,2.0,0.08,1902874.0,Adjuntas,Puerto Rico,601.0,1527.0,NaN
2,103379.0,for_sale,67000.0,2.0,1.0,0.15,1404990.0,Juana Diaz,Puerto Rico,795.0,748.0,NaN
3,31239.0,for_sale,145000.0,4.0,2.0,0.10,1947675.0,Ponce,Puerto Rico,731.0,1800.0,NaN
4,34632.0,for_sale,65000.0,6.0,2.0,0.05,331151.0,Mayaguez,Puerto Rico,680.0,NaN,NaN

In [5]:
realtor_data["state"].unique() #checking to see each unique state

<StringArray>
[         'Puerto Rico',       'Virgin Islands',        'Massachusetts',
          'Connecticut',        'New Hampshire',              'Vermont',
           'New Jersey',             'New York',       'South Carolina',
            'Tennessee',         'Rhode Island',             'Virginia',
              'Wyoming',                'Maine',              'Georgia',
         'Pennsylvania',        'West Virginia',             'Delaware',
            'Louisiana',                 'Ohio',           'California',
             'Colorado',             'Maryland',             'Missouri',
 'District of Columbia',            'Wisconsin',       'North Carolina',
             'Kentucky',             'Michigan',          'Mississippi',
              'Florida',              'Alabama',        'New Brunswick',
                    nan,                'Texas',             'Arkansas',
                'Idaho',              'Indiana',             'Illinois',
           'New Mexico',                 'Iowa',            'Minnesota',
         'South Dakota',             'Nebraska',         'North Dakota',
              'Montana',             'Oklahoma',               'Kansas',
               'Oregon',                 'Utah',               'Nevada',
           'Washington',              'Arizona',               'Hawaii',
                 'Guam',               'Alaska']
Length: 56, dtype: str

### I only want to use the 50 US states and Washington D.C. for my data and houses that have a status of sold.
I will begin cleaning the data to only contain the states by removing the US territories, after that I will remove any houses that are not currently sold so that we can begin looking at the data.

In [6]:
not_wanted = ["Puerto Rico", "Virgin Islands", "Guam", "New Brunswick"] #selecting locations to remove


fifty_states = realtor_data[~realtor_data['state'].isin(not_wanted).dropna()] #removing the locations not wanted and null values

fifty_states_sold = fifty_states[fifty_states['status'] == 'sold'] #removing the houses that are not currently sold

fifty_states_sold.head()

,brokered_by,status,price,bed,bath,acre_lot,street,city,state,zip_code,house_size,prev_sold_date
1414980,53016.0,sold,215000.0,2.0,2.0,NaN,597574.0,Agawam,Massachusetts,1001.0,1136.0,2022-04-11
1414981,8147.0,sold,232900.0,2.0,2.0,NaN,1138393.0,Agawam,Massachusetts,1001.0,1428.0,2022-04-11
1414982,48733.0,sold,975000.0,3.0,4.0,3.04,431222.0,Amherst,Massachusetts,1002.0,2074.0,2022-04-15
1414983,48733.0,sold,649900.0,4.0,3.0,0.48,1122145.0,Amherst,Massachusetts,1002.0,2650.0,2022-04-14
1414984,79067.0,sold,215000.0,3.0,2.0,0.19,697261.0,Chicopee,Massachusetts,1020.0,1828.0,2022-04-15

In [7]:
fifty_states_sold["price"].isnull().sum() #checking if there are any null values for price, we can see 245 NaN values.

np.int64(245)

In [8]:
fifty_states_sold = fifty_states_sold.dropna(subset=['price']) #removing all NaN values

In [9]:
# checking to see if there are any outliers, high and low.
fifty_states_sold['price'].sort_values() # we can see that some houses are being noted as sold at $1, and the largest house is over 200 million

1767002            1.0
1912504            1.0
1782549            1.0
1782628            1.0
1784910            1.0
              ...
2063984     64500000.0
2058881     80000000.0
1703133     80000000.0
2064065     95000000.0
2054444    295000000.0
Name: price, Length: 811157, dtype: float64

In [10]:
#we will remove the outliers of the bottom and top 5% of houses to remove huge outliers.
low_thresh = fifty_states_sold['price'].quantile(0.05) 
high_thresh = fifty_states_sold['price'].quantile(0.95)


fifty_states_sold = fifty_states_sold[(fifty_states_sold['price'] > low_thresh) & 
                                        (fifty_states_sold['price'] < high_thresh)].sort_values(by='price') #this will filter out the bottom and top 5% of houses to make the data less skewed.

print(fifty_states_sold)

         brokered_by status      price  bed  bath  acre_lot     street  \
1741939      95297.0   sold    62250.0  2.0   2.0       NaN  1443265.0
1898733      47169.0   sold    62300.0  4.0   2.0      0.32   129150.0
2046630      57824.0   sold    62300.0  NaN   NaN     10.00  1881192.0
1875534      22118.0   sold    62300.0  2.0   1.0      0.14  1721667.0
1737951      47388.0   sold    62400.0  2.0   2.0       NaN   974432.0
...              ...    ...        ...  ...   ...       ...        ...
1678792      51532.0   sold  1297000.0  5.0   6.0      0.15   915728.0
2144311      77366.0   sold  1297112.0  5.0   5.0      0.16   534605.0
1844794      10387.0   sold  1297747.0  5.0   4.0      0.07   542031.0
1562979      55026.0   sold  1297747.0  6.0   6.0      3.42   181967.0
2193696      48698.0   sold  1297995.0  4.0   3.0       NaN   421094.0

                         city       state  zip_code  house_size prev_sold_date
1741939       New Port Richey     Florida   34653.0       960.0     2022-04-18
1898733             Newcastle    Oklahoma   73065.0      1441.0     2022-03-25
2046630                Ribera  New Mexico   87560.0         NaN     2022-04-06
1875534            Wood River    Illinois   62095.0       932.0     2021-12-06
1737951               Parrish     Florida   34219.0      1456.0     2022-04-25
...                       ...         ...       ...         ...            ...
1678792       Pensacola Beach     Florida   32561.0      3476.0     2022-03-29
2144311        Mountain House  California   95391.0      3490.0     2021-12-15
1844794               Chicago    Illinois   60640.0      4089.0     2021-12-20
1562979  Lutherville Timonium    Maryland   21093.0      6194.0     2021-12-30
2193696              Bellevue  Washington   98007.0      2205.0     2022-03-31

[729878 rows x 12 columns]